import glob
import pandas as pd
import snakemake.utils

# Load fixed config parameters
configfile: "config/params.yaml"

# Get the output directory and define the structure directory
output_dir = "results/" + config.get("outdir", "results/my_results")
input_dir = f"{output_dir}/structs"
identifiers = config.get("identifiers", "identifiers.txt")


# Include rules
include: "rules/download_data.smk"
include: "rules/alignment.smk"
include: "rules/trees.smk"


rule all:
    input:
        # Download structures, wait for it to be done
        f"{output_dir}/done.txt",
        # get all sequences in a single file
        f"{output_dir}/alignment/processed_sequences.fa",

        # FoldMason alignment only
        #f"{output_dir}/alignment/foldmason/alignment_aa.fa"

        # fastME based on IMD
        #f"{output_dir}/fastME/ref_IMD.txt",
        #f"{output_dir}/fastME/FastME_IMD_final.nwk",

        # IQ-TREE results for each alphabet and model
        expand(f"{output_dir}/iqtree/3di/{{combs_3di}}.iqtree", combs_3di=config["three_di_models"]),

        # Partitioned IQ-TREE results combining LG with both 3di and AF
        expand(f"{output_dir}/iqtree_partitioned/ML_{{combs_3di}}.iqtree", combs_3di=config["three_di_models"])
 
