# PARAMS
# Output folder that will get created, can be overwritten with 
# snakemake --config output_dir="results/my_run"
outdir: 'my_result'
# Uniprot identifiers formated as one identifiers per line, can be overwritten with --config identifiers="identifiers_test.txt"
identifiers: 'identifiers.txt'

# Decide which modelfinder procedure or to use or pick a model. Full Model consideration might significantly lower speed but give better accuracy
# use modelfinder plus
ML_model: 'MFP'

# Ultrafast bootstrap iterations for iqtree
UF_boot: 1000
fastME_boot: 100

# Download pipeline, exclude structures with mean pLDDT lower than X
low_confidence: 40

# structural Alphabets and Models 
alphabets: ["aa", "3Di"]

# which 3Di ML method should be combined with the seqence based tree, available are the 3di matrix based on Puente-Lelievre et. al or the AF Matrix by Garg & Hochberg 
# where 3Di corresponds to a blosum like matrix and AF (or LLM, which are almost identical, see Garg et al.) is a full classical substition matrix
three_di_models: ["AF"]
#three_di_models: ["AF","3Di"]

# min lddt to mask residues for the seed stage in foldmason
min_lddt: 50

# Some stuff i need for the download pipeline that i adapted from foldtree, shouldnt actually do anything 
eval_both: 1e-3
coverage: 50
clean_folder: False
custom_structs: False

# substitution matrices
subst_matrix: 
  aln: 'data/subst_matrixes/mat3di.out'
  3di: 'data/subst_matrixes/3DI.nexus'
  LLM: 'data/subst_matrixes/Q_mat_LLM_Garg.txt'
  AF: 'data/subst_matrixes/Q_mat_AF_Garg.txt'


