# PARAMS
# Output folder that will get created, can be overwritten with 
# snakemake --config output_dir="results/my_run"
outdir: 'my_result'
# Uniprot identifiers formated as one identifiers per line
identifiers: 'identifiers.txt'

# Decide which modelfinder procedure or to use or pick a model. Full Model consideration might significantly lower speed but give better accuracy
# use modelfinder
# ML_model: 'MF+I+R'
ML_model: 'MFP'
# specify model, e.g. LG
# Ml_model: 'LG'
# Normal or Ultrafast bootstrap iterations for iqtree
# boot: 100
UF_boot: 1000
fastME_boot: 100

# Download pipeline, exclude structures with mean pLDDT lower than X
low_confidence: 40

# structural Alphabets and Models 
alphabets: ["aa", "3Di"]

# which 3Di ML method should be combined with the seqence based tree, available are the 3di matrix based on Puente-Lelievre et. alor the AF Matrix by Hochberg 
three_di_models: ["AF"]

# min lddt to mask residues in 3Di alignments
min_lddt: 50

# Foldtree options
clean_folder: False
custom_structs: False

# Hypothetical if i would include foldseek in the pipeline
# target per queries in both foldseek and blast
#target_seqs: 1000

#max_seqs_brh: 5

# minimum filter evalue
eval_both: 1e-3
coverage: 50
#eval_brh: 10
# how many targets to do the tree
#max_seqs: 150


# substitution matrices
subst_matrix: 
  aln: 'data/subst_matrixes/mat3di.out'
  3di: 'data/subst_matrixes/3DI.nexus'
  LLM: 'data/subst_matrixes/Q_mat_LLM_Garg.txt'
  AF: 'data/subst_matrixes/Q_mat_AF_Garg.txt'


